### ISSUE TITLE
Generic ESP32 version?

### ISSUE THREAD

**Issue by Celticpure** [MicroMidi/NUX-MIDI-Footswitch#1]
Any plans to release a generic ESP23 version for those not using the HELTEC boards?? Thank you for your hard work!

**Comment by MicroMidi** [comment]
That should be possible - if an external SSD1306 OLED display will be attached to the ESP32 controller. Does this scenario match to your requirement?

**Comment by Celticpure** [comment]
Yes that would be exactly my scenario. Thank you.

**Comment by MicroMidi** [comment]
At least I have managed so far to modify the code in order to use the generic ESP32 board software and an external SSD1306 OLED library with my "Heltec ESP32 WiFi kit". So there are no longer any dependencies to Heltec software components and the code should work with all generic ESP32 devices that have an SSD1306 OLED display attached which is connected via I2C interface to the ESP32 module.

Final tests will be processed with an ESP32 WROVER module if my external SSD1306 display unit arrives that I ordered a couple of days ago.

So it seems that generic ESP32 support is almost close to release …

**Comment by Celticpure** [comment]
Wow! Awesome work thank you for this. I will try and 1106 board also when I get back from holidays and let you know. It should work ok.

**Comment by MicroMidi** [comment]
Everything works as expected in my new test environment - so I published a first version for generic ESP32 modules with an external SSD1306 OLED device attached. Any feedback if this works in your environment is highly appreciated.

**Comment by Celticpure** [comment]
Awesome, thank you so much. I will test in the next week or so and report back. Looking forward to this!

**Comment by MicroMidi** [comment]
@Celticpure: Any results on testing the ESP32 version in your environment, yet?

**Comment by Celticpure** [comment]
Yes the esp32 connects to the app fine. However the switches cannot change the banks. Nothing happens. I have rechecked the code to ensure correct pin assignment to the switches. Not sure what I might be missing here?

**Comment by MicroMidi** [comment]
... the esp32 should connect directly to the Mighty Plug - the "Mightier" app is not needed in this setup. If this is the case in your scenario please doublecheck if the push buttons are tied to GND and not to VCC. The code initializes the ESP32-PINS for the push buttons with the "pull-up" feature. Hence, they are on VCC-level if they are not pushed. The push operation should change the level to GND and therefore the connection to GND is required. You can see that on the wiring scheme in the project description. Hope this helps ...

**Comment by MicroMidi** [comment]
@Celticpure: Any need for further assistance or did you manage to get this to work?

**Comment by MicroMidi** [comment]
"No news is good news" ...
No further response, I close this issue now with status "solved"

**Comment by MicroMidi** [comment]
"No news is good news" ...
No further response, I close this issue now with status "solved"
